apiVersion: v2
name: tiktok-clone
description: A Helm chart for TikTok Clone microservices on Kubernetes
type: application
version: 1.0.0
appVersion: '1.0.0'
keywords:
  - tiktok-clone
  - microservices
  - kubernetes
  - nestjs
maintainers:
  - name: Senior Developer
    email: dev@tiktok-clone.local
