global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:5555']
        labels:
          service: 'api-gateway'

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
        labels:
          service: 'auth-service'

  - job_name: 'video-service'
    static_configs:
      - targets: ['video-service:3002']
        labels:
          service: 'video-service'

  - job_name: 'interaction-service'
    static_configs:
      - targets: ['interaction-service:3003']
        labels:
          service: 'interaction-service'
